### ISSUE TITLE
Allows installation via composer

### ISSUE THREAD

**Issue by GeeH** [php-school/learn-you-php#65]
Composer global require is a cool way to make the workshop manager available to the entire system without all that messing about with curl and chmod. It's easy enough to do this, if someone says it would be useful, I will make it so...

**Comment by AydinHassan** [comment]
Sorry for late reply, been climbing Ben Nevis 😄. I don't see why not. We orignally had each workshop as global installs but we had some dependency clashes and people complained. That's why when made the workshop manager we made it as a phar. I think it would be fine to offer as a global install also. Should just require some small changes to composer file and a tag. Although we might want to disable the phar update/rollback commands when not in phar mode.

Workshop manager can be found here: https://github.com/php-school/workshop-manager 😀

**Comment by AydinHassan** [comment]
The workshop manager can now be installed via `composer global require php-school/workshop-manager`
